query GetThreeDs ($first: Int, $last: Int, $after: String, $before: String) {
  threeds (first: $first, last: $last, after: $after, before: $before) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
      node {
        content
        contentTypeName
        # databaseId
        # date
        # dateGmt
        # desiredSlug
        # enclosure
        # guid
        id
        # isContentNode
        # isPreview
        # isRestricted
        # isTermNode
        link
        # modified
        # modifiedGmt
        # previewRevisionDatabaseId
        # previewRevisionId
        slug
        status
        # template {
        #   templateName
        # }
        title
        uri
        # custom fields
        threedId
        # threedBgColor
        # threedBgImage {
        #   node {
        #     id
        #     link
        #     mediaItemId
        #     mediaItemUrl
        #     mediaType
        #     mediaDetails {
        #       file
        #       height
        #       width
        #     }
        #   }
        # }
        # threedBgImageNx {
        #   node {
        #     mediaItemId
        #     mediaItemUrl
        #     mediaType
        #     mediaDetails {
        #       file
        #       height
        #       width
        #     }
        #     sourceUrl
        #     title
        #     uri
        #     link
        #     slug
        #   }
        # }
        # threedBgImageNy {
        #   node {
        #     mediaItemId
        #     mediaItemUrl
        #     mediaType
        #     mediaDetails {
        #       file
        #       height
        #       width
        #     }
        #     sourceUrl
        #     title
        #     uri
        #     link
        #     slug
        #   }
        # }
        # threedBgImageNz {
        #   node {
        #     mediaItemId
        #     mediaItemUrl
        #     mediaType
        #     mediaDetails {
        #       file
        #       height
        #       width
        #     }
        #     sourceUrl
        #     title
        #     uri
        #     link
        #     slug
        #   }
        # }
        # threedBgImagePx {
        #   node {
        #     mediaItemId
        #     mediaItemUrl
        #     mediaType
        #     mediaDetails {
        #       file
        #       height
        #       width
        #     }
        #     sourceUrl
        #     title
        #     uri
        #     link
        #     slug
        #   }
        # }
        # threedBgImagePy {
        #   node {
        #     mediaItemId
        #     mediaItemUrl
        #     mediaType
        #     mediaDetails {
        #       file
        #       height
        #       width
        #     }
        #     sourceUrl
        #     title
        #     uri
        #     link
        #     slug
        #   }
        # }
        # threedBgImagePz {
        #   node {
        #     mediaItemId
        #     mediaItemUrl
        #     mediaType
        #     mediaDetails {
        #       file
        #       height
        #       width
        #     }
        #     sourceUrl
        #     title
        #     uri
        #     link
        #     slug
        #   }
        # }
        # threedPlaneWidthX
        # threedPlaneHeightY
        # threedPlaneLengthZ
        # threedPlaneTextureRepeatX
        # threedPlaneTextureRepeatY
        # threedPlaneTextureRepeatZ
        # threedPlaneTextureImage {
        #   node {
        #     mediaDetails {
        #       file
        #       height
        #       width
        #     }
        #     link
        #     slug
        #     sourceUrl
        #     title
        #     uri
        #   }
        # }
      }
    }
  }
  # allotments {
  #   nodes
  # }
  # beds {
  #   nodes
  # }
  # plants {
  #   nodes
  # }
}

# GQL QUERY RETURNS: {.json}
# {
#   "data": {
#     "threeds": {
#       "pageInfo": {
#         "endCursor": "YXJyYXljb25uZWN0aW9uOjc4",
#         "hasNextPage": false,
#         "hasPreviousPage": false,
#         "startCursor": "YXJyYXljb25uZWN0aW9uOjc4"
#       },
#       "edges": [
#         {
#           "cursor": "YXJyYXljb25uZWN0aW9uOjc4",
#           "node": {
#             "content": "\n<p>Private home set of 2 gardening allotments, 1 hen house, 1 greenhouse, 1 power station, in Inglenook, California.</p>\n",
#             "contentTypeName": "threed_threed",
#             "id": "cG9zdDo3OA==",
#             "link": "https://threed.design.local/threed-threed/mcgee-home-garden/",
#             "threedBgColor": "#333333",
#             "threedBgImage": {
#               "node": {
#                 "id": "cG9zdDo4Mw==",
#                 "link": "https://threed.design.local/threed-threed/mcgee-home-garden/idahomeadow_01-scaled/",
#                 "mediaItemId": 83,
#                 "mediaItemUrl": "https://threed.design.local/wp-content/uploads/2022/09/idahomeadow_01-scaled-1.jpg",
#                 "mediaType": "image",
#                 "mediaDetails": {
#                   "file": "2022/09/idahomeadow_01-scaled-1.jpg",
#                   "height": 561,
#                   "width": 2560
#                 }
#               }
#             },
#             "threedBgImageNx": {
#               "node": {
#                 "mediaItemId": 84,
#                 "mediaItemUrl": "https://threed.design.local/wp-content/uploads/2022/09/nx.png",
#                 "mediaType": "image",
#                 "mediaDetails": {
#                   "file": "2022/09/nx.png",
#                   "height": 512,
#                   "width": 512
#                 },
#                 "sourceUrl": "https://threed.design.local/wp-content/uploads/2022/09/nx.png",
#                 "title": "nx",
#                 "uri": "/threed-threed/mcgee-home-garden/nx/",
#                 "link": "https://threed.design.local/threed-threed/mcgee-home-garden/nx/",
#                 "slug": "nx"
#               }
#             },
#             "threedBgImageNy": {
#               "node": {
#                 "mediaItemId": 85,
#                 "mediaItemUrl": "https://threed.design.local/wp-content/uploads/2022/09/ny.png",
#                 "mediaType": "image",
#                 "mediaDetails": {
#                   "file": "2022/09/ny.png",
#                   "height": 512,
#                   "width": 512
#                 },
#                 "sourceUrl": "https://threed.design.local/wp-content/uploads/2022/09/ny.png",
#                 "title": "ny",
#                 "uri": "/threed-threed/mcgee-home-garden/ny/",
#                 "link": "https://threed.design.local/threed-threed/mcgee-home-garden/ny/",
#                 "slug": "ny"
#               }
#             },
#             "threedBgImageNz": {
#               "node": {
#                 "mediaItemId": 86,
#                 "mediaItemUrl": "https://threed.design.local/wp-content/uploads/2022/09/nz.png",
#                 "mediaType": "image",
#                 "mediaDetails": {
#                   "file": "2022/09/nz.png",
#                   "height": 512,
#                   "width": 512
#                 },
#                 "sourceUrl": "https://threed.design.local/wp-content/uploads/2022/09/nz.png",
#                 "title": "nz",
#                 "uri": "/threed-threed/mcgee-home-garden/nz/",
#                 "link": "https://threed.design.local/threed-threed/mcgee-home-garden/nz/",
#                 "slug": "nz"
#               }
#             },
#             "threedBgImagePx": {
#               "node": {
#                 "mediaItemId": 87,
#                 "mediaItemUrl": "https://threed.design.local/wp-content/uploads/2022/09/px.png",
#                 "mediaType": "image",
#                 "mediaDetails": {
#                   "file": "2022/09/px.png",
#                   "height": 512,
#                   "width": 512
#                 },
#                 "sourceUrl": "https://threed.design.local/wp-content/uploads/2022/09/px.png",
#                 "title": "px",
#                 "uri": "/threed-threed/mcgee-home-garden/px/",
#                 "link": "https://threed.design.local/threed-threed/mcgee-home-garden/px/",
#                 "slug": "px"
#               }
#             },
#             "threedBgImagePy": {
#               "node": {
#                 "mediaItemId": 88,
#                 "mediaItemUrl": "https://threed.design.local/wp-content/uploads/2022/09/py.png",
#                 "mediaType": "image",
#                 "mediaDetails": {
#                   "file": "2022/09/py.png",
#                   "height": 512,
#                   "width": 512
#                 },
#                 "sourceUrl": "https://threed.design.local/wp-content/uploads/2022/09/py.png",
#                 "title": "py",
#                 "uri": "/threed-threed/mcgee-home-garden/py/",
#                 "link": "https://threed.design.local/threed-threed/mcgee-home-garden/py/",
#                 "slug": "py"
#               }
#             },
#             "threedBgImagePz": {
#               "node": {
#                 "mediaItemId": 89,
#                 "mediaItemUrl": "https://threed.design.local/wp-content/uploads/2022/09/pz.png",
#                 "mediaType": "image",
#                 "mediaDetails": {
#                   "file": "2022/09/pz.png",
#                   "height": 512,
#                   "width": 512
#                 },
#                 "sourceUrl": "https://threed.design.local/wp-content/uploads/2022/09/pz.png",
#                 "title": "pz",
#                 "uri": "/threed-threed/mcgee-home-garden/pz/",
#                 "link": "https://threed.design.local/threed-threed/mcgee-home-garden/pz/",
#                 "slug": "pz"
#               }
#             },
#             "threedId": 78,
#             "threedPlaneWidthX": 300,
#             "threedPlaneHeightY": 300,
#             "threedPlaneLengthZ": 0,
#             "threedPlaneTextureRepeatX": 4,
#             "threedPlaneTextureRepeatY": 4,
#             "threedPlaneTextureRepeatZ": 0,
#             "threedPlaneTextureImage": {
#               "node": {
#                 "mediaDetails": {
#                   "file": "2022/09/grasslight-big.jpg",
#                   "height": 2048,
#                   "width": 2048
#                 },
#                 "link": "https://threed.design.local/threed-threed/mcgee-home-garden/grasslight-big/",
#                 "slug": "grasslight-big",
#                 "sourceUrl": "https://threed.design.local/wp-content/uploads/2022/09/grasslight-big.jpg",
#                 "title": "grasslight-big",
#                 "uri": "/threed-threed/mcgee-home-garden/grasslight-big/"
#               }
#             },
#             "slug": "mcgee-home-garden",
#             "status": "publish",
#             "title": "McGee Home Garden",
#             "uri": "/threed-threed/mcgee-home-garden/"
#           }
#         }
#       ]
#     }
#   },
#   "extensions": {
#     "debug": []
#   }
# }
